version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/myapp1.war
    - appspec.yml
    - scripts/after_install.sh
    - scripts/application_start.sh
    - scripts/application_stop.sh
    - scripts/before_install.sh